import type { Metadata } from "next";
import LegalPage from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Terms of service",
  description: "The legal terms that govern your use of Veyago.",
};

export default function Terms() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Terms of service"
      effectiveDate="24 April 2026"
      lastUpdated="24 April 2026"
    >
      <div className="legal-plain">
        <strong>The short version.</strong> These are the rules for using Veyago. Be 16 or older, use the app honestly, don't try to break it, and remember that destination suggestions are suggestions, not guarantees. If there's ever a serious dispute, New York law applies — but if you're a consumer in Europe or the UK, your local consumer protection rights still apply in full.
      </div>

      <h2>1. Agreement</h2>
      <p>
        These Terms of Service (the "Terms") are a contract between you and <strong>Veyago Inc.</strong>, a New York corporation with operational headquarters in Belgium ("Veyago", "we", "us"). They govern your use of our mobile apps, our website at veyago.app, and everything we build on top of them (together, the "Service").
      </p>
      <p>By creating an account, installing our app, or using the Service, you agree to these Terms. If you don't agree, please don't use the Service.</p>

      <h2>2. Who can use Veyago</h2>
      <div className="legal-plain">
        You need to be 16 or older. One account per person. You're responsible for what happens under your account.
      </div>
      <p>You must be <strong>at least 16 years old</strong> to create an account. By signing up you represent that you are 16 or older and have the legal capacity to enter into these Terms.</p>
      <p>You are responsible for keeping your login credentials secure and for all activity under your account. Tell us immediately at <a href="mailto:hello@veyago.app">hello@veyago.app</a> if you suspect unauthorised access.</p>
      <p>One human, one account. Don't impersonate anyone. Don't create an account for anyone else without their knowledge and permission.</p>

      <h2>3. What the Service is (and isn't)</h2>
      <p>Veyago helps you discover travel destinations through swipes, brackets, and group sessions, and optionally maps places you've been. We may also recommend experiences and accommodations through affiliate links and suggest itineraries generated by AI.</p>
      <p><strong>We are not a travel agent, booking platform, or tour operator.</strong> When you click through to a partner like Booking.com, Skyscanner, or GetYourGuide, you are contracting with that partner, not us. Their terms, prices, availability, refund policies, cancellation rules, and customer service apply.</p>
      <p><strong>Destination content is informational.</strong> Visa requirements, opening hours, safety conditions, pricing, and availability change constantly. Always verify critical details with official sources before booking or travelling.</p>

      <h2>4. AI features</h2>
      <p>If you use our AI itinerary feature, we send your destination and preferences (no identifying information) to <strong>OpenAI's GPT-4o</strong> to generate a suggested plan. Under EU AI Act Article 50, we confirm: <strong>the output is artificially generated</strong>. It is a suggestion, not professional travel advice. Verify the details before relying on them.</p>

      <h2>5. Acceptable use</h2>
      <div className="legal-plain">
        Don't use Veyago to harm other people, scrape our data, break the law, or bypass our systems.
      </div>
      <p>You agree not to:</p>
      <ul>
        <li>break any law or regulation or help anyone else break one;</li>
        <li>harass, threaten, defame, or abuse other users or Veyago staff;</li>
        <li>upload content that is illegal, infringing, obscene, or that you don't have rights to;</li>
        <li>impersonate anyone or misrepresent your affiliation with any person or organisation;</li>
        <li>scrape, crawl, or use automated means to extract data from the Service beyond what our public APIs explicitly allow;</li>
        <li>reverse engineer, decompile, or attempt to derive the source code of the Service, except to the extent this restriction is prohibited by applicable law;</li>
        <li>probe, scan, or test the vulnerability of the Service except under our Responsible Disclosure policy;</li>
        <li>circumvent authentication, rate limits, or access controls;</li>
        <li>resell, sublicense, or commercially exploit the Service without our written permission;</li>
        <li>use the Service to send spam, run a competing product, or train machine learning models on our content.</li>
      </ul>
      <p>We can suspend or terminate accounts that violate these rules. In serious cases we may report violations to law enforcement.</p>

      <h2>6. User content</h2>
      <div className="legal-plain">
        You own your profile photo. By uploading it you give us the limited permission we need to display it in the app. You can delete it any time.
      </div>
      <p>The only user-uploaded content in Veyago v1.0 is your <strong>profile photo</strong>.</p>
      <p>You keep all rights to your profile photo. By uploading it you grant Veyago a <strong>worldwide, non-exclusive, royalty-free licence</strong> to host, store, display, resize, and transmit it within the Service, for the sole purpose of operating the Service. This licence ends when you delete the photo or your account.</p>
      <p>You represent that you own or have permission to use any photo you upload, and that it doesn't infringe anyone else's rights.</p>

      <h2>7. Copyright and DMCA</h2>
      <p>If you believe content on the Service infringes your copyright, see our <strong>DMCA Policy</strong> at <a href="/dmca">veyago.app/dmca</a> for how to file a takedown notice. We terminate the accounts of repeat infringers.</p>

      <h2>8. Intellectual property</h2>
      <div className="legal-plain">
        Veyago's brand, code, and content are ours. You get a licence to use the app, not to own it.
      </div>
      <p>Veyago owns the Service, including its software, design, trademarks, logos, destination photography (licensed or created by us), and all other content that isn't yours. We grant you a <strong>limited, personal, non-exclusive, non-transferable, revocable licence</strong> to use the Service for your own non-commercial travel planning.</p>
      <p>"Veyago" and the Veyago logo are our trademarks. Don't use them without written permission.</p>

      <h2>9. Subscriptions and payments</h2>
      <div className="legal-plain">
        Premium is a paid, auto-renewing subscription billed through the App Store, Google Play, or Stripe. Cancel any time in your app store account or via our website — cancellation stops the next renewal, not the current period.
      </div>
      <p>Some features are free; others require a <strong>Premium subscription</strong>. When you buy Premium:</p>
      <ul>
        <li>The price, billing period, and included features are shown before you confirm.</li>
        <li><strong>Your subscription renews automatically</strong> at the end of each period unless you cancel at least <strong>24 hours</strong> before the renewal date.</li>
        <li>Cancel through your <strong>Apple ID subscriptions</strong>, <strong>Google Play subscriptions</strong>, or — for Stripe subscriptions — through your Veyago account page. Cancellation stops future renewals; it does not refund the current period.</li>
        <li>Prices may change. We'll tell you at least <strong>30 days</strong> in advance, and you can cancel before the change takes effect.</li>
      </ul>
      <p><strong>EU / UK right of withdrawal.</strong> If you are a consumer in the EU or UK, you have a statutory <strong>14-day right of withdrawal</strong> after purchase. By subscribing and accessing Premium features during the withdrawal period, you expressly request that the Service be supplied immediately and acknowledge that you lose the right of withdrawal once the Service has been fully performed (Article 16(m) of Directive 2011/83/EU). Before that point, email <a href="mailto:hello@veyago.app">hello@veyago.app</a> to exercise the right.</p>

      <h2>10. Affiliate links</h2>
      <p>Some outbound links earn us a commission — Booking.com, Skyscanner/Travelpayouts, GetYourGuide and similar partners. We disclose this openly in our <strong>Affiliate Disclosure</strong> at <a href="/affiliates">veyago.app/affiliates</a>. Affiliate relationships <strong>do not</strong> influence what our matching engine recommends to you.</p>

      <h2>11. Third-party services</h2>
      <p>The Service integrates with third parties (Supabase, OpenAI, PostHog, Sentry, Stripe, Apple, Google, Resend, Mapbox, Cloudflare, and our affiliate partners). We are not responsible for outages, errors, or policy changes in third-party services, though we'll do our reasonable best to route around them.</p>

      <h2>12. Termination</h2>
      <p>You can delete your account at any time in Settings, or by emailing <a href="mailto:hello@veyago.app">hello@veyago.app</a>. We delete your data according to the schedule in our Privacy Policy.</p>
      <p>We can suspend or terminate your account with or without notice if you breach these Terms, if required by law, or if we reasonably believe your use creates risk or legal exposure for us, other users, or third parties.</p>

      <h2>13. Disclaimers</h2>
      <div className="legal-plain">
        Veyago is provided as-is. Travel is complicated, the world changes, and our recommendations are suggestions. Verify anything important before you travel.
      </div>
      <p><strong>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND</strong>, including merchantability, fitness for a particular purpose, non-infringement, and accuracy of content. We don't warrant that the Service will be uninterrupted, error-free, or secure.</p>
      <p><strong>Nothing in these Terms excludes or limits liability that cannot be excluded by law</strong> — including, for EU and UK consumers, statutory consumer rights, liability for fraud, gross negligence, or death or personal injury caused by our negligence.</p>

      <h2>14. Limitation of liability</h2>
      <div className="legal-plain">
        If something goes wrong because of us, our total liability is capped — for free users at €100, for paying users at the amount you paid us in the 12 months before the problem. None of this reduces rights you have as an EU or UK consumer that can't be waived.
      </div>
      <p><strong>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW</strong>, in no event will Veyago be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, including loss of profits, goodwill, data, or travel plans.</p>
      <p>Our total aggregate liability is limited to the greater of <strong>(a) €100</strong> or <strong>(b) the amount you paid Veyago in the 12 months preceding the event giving rise to the claim</strong>.</p>
      <p><strong>EU and UK consumer rights.</strong> If you are a consumer in the EU or UK, nothing in this section limits your non-waivable statutory rights.</p>

      <h2>15. Indemnification</h2>
      <p>If you break these Terms, break the law, or infringe someone's rights in a way that causes a claim against us, you agree to defend, indemnify, and hold Veyago harmless from reasonable costs, damages, and attorneys' fees. This does not apply to EU/UK consumers to the extent prohibited by applicable consumer protection law.</p>

      <h2>16. Governing law and dispute resolution</h2>
      <div className="legal-plain">
        New York law governs these Terms. For most disputes we'd rather talk it out first. EU and UK consumers keep their home-country court rights.
      </div>
      <p><strong>Governing law.</strong> These Terms are governed by the internal laws of the <strong>State of New York</strong>, without regard to conflict-of-laws principles.</p>
      <p><strong>Informal resolution first.</strong> Before filing anything formal, please email <a href="mailto:hello@veyago.app">hello@veyago.app</a> with a clear description of the problem. We commit to a good-faith response within 30 days.</p>
      <p><strong>EU and UK consumers.</strong> If you are a consumer habitually resident in the EU or UK, you can bring proceedings in the courts of your country of residence, and the mandatory consumer protection law of that country applies to you. EU consumers may also use the European Commission's <a href="https://ec.europa.eu/consumers/odr" rel="noreferrer">Online Dispute Resolution platform</a>.</p>
      <p><strong>All other users — binding arbitration.</strong> Any dispute that cannot be resolved informally within 30 days will be resolved by <strong>binding individual arbitration</strong> administered by the <strong>American Arbitration Association</strong> under its Consumer Arbitration Rules. The arbitration will be held in <strong>New York County, New York</strong>, or remotely at the consumer's request.</p>
      <p><strong>Class action waiver.</strong> Each party may bring claims only in an individual capacity, not as a class member in any purported class or representative proceeding.</p>
      <p><strong>30-day opt-out.</strong> You may opt out of arbitration within 30 days of first accepting these Terms by emailing <a href="mailto:hello@veyago.app">hello@veyago.app</a> with "Arbitration opt-out" in the subject line.</p>

      <h2>17. Changes to these Terms</h2>
      <p>For material changes, we'll give at least <strong>14 days' notice</strong> by email and in-app. Continuing to use the Service after the effective date means you accept the changes.</p>

      <h2>18. Miscellaneous</h2>
      <p>These Terms, together with the Privacy Policy and any policies referenced here, are the entire agreement between you and Veyago about the Service. If any provision is unenforceable, the rest still applies. Notices to Veyago: <a href="mailto:hello@veyago.app">hello@veyago.app</a>.</p>

      <h2>19. Contact</h2>
      <p><strong>Veyago Inc.</strong> — Belgium (operational HQ) / New York, USA (incorporated) — <a href="mailto:hello@veyago.app">hello@veyago.app</a></p>
    </LegalPage>
  );
}
